name: Terraform Apply

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
  Terraform_Apply:
    runs-on: ubuntu-latest
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: '${{ secrets.TF_USER_AWS_KEY }}'
          aws-secret-access-key: '${{ secrets.TF_USER_AWS_SECRET }}'
          aws-region: eu-west-2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
      - name: Set environment variables
        run: |
          echo "AWS_PROFILE=${{ secrets.AWS_PROFILE }}" >> $GITHUB_ENV

      - name: Terraform Apply
        id: apply
        run:  |
          cd tf-code/
          RETRIES=5
          for i in $(seq 1 $RETRIES); do
            terraform init -backend-config="profile=${{ secrets.AWS_PROFILE }}"
          done
          terraform validate
          terraform plan
          terraform apply -auto-approve