name: Terraform Destroy

on:
  workflow_dispatch:

jobs:
  Terraform_Destroy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: '${{ secrets.TF_USER_AWS_KEY }}'
          aws-secret-access-key: '${{ secrets.TF_USER_AWS_SECRET }}'
          aws-region: eu-west-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Set environment variables
        run: |
          echo "AWS_PROFILE=${{ secrets.AWS_PROFILE }}" >> $GITHUB_ENV

      - name: Terraform Destroy
        id: destroy
        run:  |
          cd tf-code/
          RETRIES=5
          for i in $(seq 1 $RETRIES); do
            terraform init -backend-config="profile=${{ secrets.AWS_PROFILE }}"
          done
          terraform destroy -auto-approve